### ISSUE TITLE
Scaling width of nft using calc() not proportional 

### ISSUE THREAD

**Issue by havealoha** [input-output-hk/lace#147]
In the Lace NFT UI elements, the use of width calc(100% + 2px) after doing the same in height results in disproportionate dimensions which make the nft look dithered.

**Comment by marcin-mazurek** [comment]
Hey @havealoha, thanks for the report, we will investigate this.

For additional background, here are some screenshots of the issue from Discord chat:
![image](https://github.com/input-output-hk/lace/assets/6684554/abf355b4-7921-46c4-9268-19a10fbb596b)

Without the calc expression:
![image](https://github.com/input-output-hk/lace/assets/6684554/16431524-cea6-4be6-be12-0e42de9c19c1)

**Comment by marcin-mazurek** [comment]
@havealoha do you happen to have a higher quality screenshots, as the ones I found on Discord are too small to see the issue clearly?

**Comment by havealoha** [comment]
I can see it fine in the shots you posted above.

**Comment by havealoha** [comment]
Here is something zoomed in, left side is skewed, right side is correct proportion.
![handle](https://github.com/input-output-hk/lace/assets/112902827/f2bb82e0-7c4c-4893-b30d-885af860489a)

**Comment by allanleone** [comment]
A few comments to add to the discussion:  If I disabled all visual enhancements of the OS, and without the kerning/smoothness, combined with no hardware acceleration on chrome, any content will look very pixelated (in special high contrast ones, like the handle text), and this could be one of possible reasons why that's happening with handle names and the container borders. Screen resolution/density could also affect the rendering of those as well.

related to the proportion, the changes to width 100% (removing the calc, from this branch, seems to fix it, but a disclaimer, if any NFT image have a different aspect ratio from 1:1, it will deform the image while forcing to be squared -- since height it's also set to 100%. (TBH I don’t know how often a NFT can be non-squared)

if required, one possible alternative would be to create a square and adjustable container, and apply the image as background, with the “background-size: cover; and background-position: center center;” – it crops the non-squared images, but keeps the proportion (something similar it’s being tested/prototyped internally)

so I believe it’s just a matter of evaluate if that’s not necessary, and if the “squared shape” covers all, then it’s all good to proceed with the merging 👍

**Comment by marcin-mazurek** [comment]
Issue fixed - it will be shipped in the next release (1.3).

**Comment by havealoha** [comment]
This is not fixed. Example: 
![image](https://github.com/input-output-hk/lace/assets/112902827/d4a71bd1-2519-4db2-84b2-5920c2f6ff12)

**Comment by havealoha** [comment]
@marcin-mazurek , see above, there are multiple places in the UI that need the treatment other than the main screen.
